name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Get dependencies again
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: motivo-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
